name = "foodshare"
compatibility_date = "2023-12-01"

# Pages 项目配置 - 用于静态网站部署
pages_build_output_dir = "dist"

# 构建配置
[build]
command = "npm run build"

# KV 命名空间绑定 - 用于应用数据存储
[[kv_namespaces]]
binding = "FOODSHARE_DATA"
id = "f5b0962a0fd1417babacb8b35ae1514b"

# 环境变量
[vars]
API_VERSION = "1.0.0"
